[project]
name = "llm-emotion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-generativeai>=0.8.5",
    "lxml>=6.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
